### ISSUE TITLE
Storing Objects

### ISSUE THREAD

**Issue by crisward** [kemalcr/kemal-session-file#1]
Suggestion

It would be good if the session engines could store objects, or anything which has a to_json method on it (ie hashes etc).

~~Also is there any documentation on how to write a session plugin, thinking of doing one with mysql via crystal-mysql, if not I could probably base it on this one.~~ Just found your wiki page.

**Comment by sdogruyol** [comment]
Please take a look at https://github.com/kemalcr/kemal-session/wiki/Creating-your-session-engine

**Comment by Thyra** [comment]
@crisward We just had the exact same idea yesterday :-D. We are implementing it right now, feel free to share your thoughts: https://github.com/kemalcr/kemal-session/pull/13

**Comment by sdogruyol** [comment]
This is now fixed with #3
