### ISSUE TITLE
Update to support kemal-session v0.5.0

### ISSUE THREAD

**Issue by sdogruyol** [kemalcr/kemal-session-file#2]
The title is self explanatory

//cc @neovintage

**Comment by crisward** [comment]
Could be worth linking session engines to specific releases of kemal-session in the future via the shards file. At the moment this is broken as it's dependency is master, so I'm unable to push builds. It's not urgent as I'm just messing, but thought worth mentioning.

**Comment by sdogruyol** [comment]
Fixed via #3
