### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by crisward** [kemalcr/kemal-session-file#9]
Timeout is based on mtime of file
https://github.com/kemalcr/kemal-session-file/blob/master/src/kemal-session-file.cr#L89

However this will only be updated if the session is updated, causing the session to timeout even if the user is active, but doesn't update any session values. Not sure how expensive it is to touch the file each time the middleware is ran, but that could be the only way of keeping this up to date.

**Comment by crisward** [comment]
I'm adding this line to my fork to help update mtime
https://github.com/crisward/kemal-session-file/blob/master/src/kemal-session-file.cr#L124

I'll let you know if it works. There isn't a FileUtils.touch in crystal, so open close seems the only option.

**Comment by neovintage** [comment]
@crisward can you copy this issue over to `kemal-session` repo? We've included the file storage engine in `kemal-session`. Thanks!

**Comment by crisward** [comment]
Done - thanks. Didn't spot the updated readme.
